### ISSUE TITLE
changes behavior of 'enter' key

### ISSUE THREAD

**Issue by sandover** [odyssomay/sublime-lispindent#1]
Mac OS X 10.8.2

I believe this package changes the behavior of the enter key in at least two ways:
1.  enter key can no longer be used to accept an auto-complete options.  Instead, it dismisses the auto-complete pop-over.
2.  enter key can no longer be used to trigger a search from the search panel.  Hitting enter after typing in a search term would normally start the search, or go to the next search hit (the same as hitting super-G); now it doesn't.

After uninstalling the package and restarting ST2, normal enter key behavior is back.

**Comment by odyssomay** [comment]
Hmm. This is definitely an issue.

The interesting part is that I'm using the exact same command 
as is used by default when pressing `enter`.

Will try to look into this further.

Current workarounds:
- Change the lispindent key binding from `enter` to something else (for example `ctrl+enter`)
- For 1. Press shift+enter instead.
  For 2. Set `auto_complete_commit_on_tab` to true in the options.

**Comment by odyssomay** [comment]
Sorry for leaving this open for so long.

This should be fixed since 29f338d.

**Comment by odyssomay** [comment]
I realized that the osx keybinds still had the old `enter` keybind.
I think this should be solved in 36fef0e - where I simply removed
the keybind completely (for osx). It should then use the keybind 
defined in the platform-independent keybind file, but I haven't
tested this.

**Comment by madnl** [comment]
I can still see the modified behavior for the enter key in the latest commit 3f99bb4ee779df091bbc1acf4de5214dc23650e0. When the autocomplete appears pressing enter on an entry will insert a newline instead of only selecting the entry and inserting it.

**Comment by odyssomay** [comment]
That's odd.

Are you on osx? In that case, can you check if the `enter` key is bound in `Preferences->Lispindent->Key Bindings - OSX`?

**Comment by odyssomay** [comment]
Actually, that issue was never solved. Sorry about that. Should be fixed now.

**Comment by madnl** [comment]
It seems to be fixed now, thanks !

**Comment by odyssomay** [comment]
That's good to hear. :)
